### ISSUE TITLE
Update position / orientation

### ISSUE THREAD

**Issue by reinvanoyen** [spite/THREE.DecalGeometry#9]
First of all, thank you for your amazing work on this Geometry. However, it's not quiet clear to me how I can update the geometry with a new position and orientation. I'm trying to update the decal as you move your mouse over the mesh. I'm quite new to this whole 3d thing with matrices etc, so it's most probably just me not knowing how to exactly use the provided methods.

To work around my issue I'm basically adding the decal and removing it again every frame, which sounds like a really bad idea:
```javascript
scene.remove( decal );
decal = new THREE.Mesh( new THREE.DecalGeometry( mesh, position, orientation, size), decalMaterial.clone() );
scene.add( decal );
```
If you could point me in the right direction, I would be very grateful.

Best,
Rein

**Comment by spite** [comment]
Yes, that's exactly right. The Decal Geometry is created by intersecting a volume against the meshes, so it's not trivial to update; the solution (for this method) is to delete and create the mesh anew. There's an example in the the demos folder, called intersect.html that shows how to do it.

Yes, it's a bad idea, but it's designed to create more or less a few static decals. For dynamic decals, it should probably be done in-shader, and it would be more expensive but more flexible. It would also need a tighter integration with the rendering pipeline.

**Comment by reinvanoyen** [comment]
Thank you for your very quick response and insight. For now I'm rolling with recreating the decal, performance wise it doesn't affect my application that much.
